-- Auto-generated by scripts/generate_postgres_schema_from_csv.py
-- Review column types before production cutover.

CREATE SCHEMA IF NOT EXISTS "mongo_import";

-- SKIPPED bookmarks.csv (reason=empty_header)
-- Source: carddrops.csv (rows=760)
CREATE TABLE IF NOT EXISTS "mongo_import"."carddrops" (
  "_id" text,
  "userId" text,
  "cardId" text,
  "dropType" text,
  "dailyDropCount" bigint,
  "craftingAttempt.usedCards" jsonb,
  "droppedAt" timestamptz,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint,
  "craftingAttempt.wasSuccessful" boolean
);
CREATE INDEX IF NOT EXISTS "idx_carddrops_id" ON "mongo_import"."carddrops" ("_id");

-- Source: cards.csv (rows=86)
CREATE TABLE IF NOT EXISTS "mongo_import"."cards" (
  "_id" text,
  "cardId" text,
  "name" text,
  "type" text,
  "rarity" text,
  "description" text,
  "imageUrl" text,
  "member" text,
  "year" bigint,
  "version" bigint,
  "isGroupCard" boolean,
  "dropRate" numeric,
  "canBeUsedForCrafting" boolean,
  "craftingRecipe.requiredCards" jsonb,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint,
  "period" text,
  "cardImageUrl" text,
  "maxCopies" bigint
);
CREATE INDEX IF NOT EXISTS "idx_cards_id" ON "mongo_import"."cards" ("_id");

-- SKIPPED discordbotstatuses.csv (reason=empty_header)
-- SKIPPED discordcommandlogs.csv (reason=empty_header)
-- Source: discordlinks.csv (rows=5)
CREATE TABLE IF NOT EXISTS "mongo_import"."discordlinks" (
  "_id" text,
  "discordId" text,
  "__v" bigint,
  "createdAt" timestamptz,
  "discordAvatar" text,
  "discordUsername" text,
  "updatedAt" timestamptz,
  "wikiLinkedAt" timestamptz,
  "wikiUserId" text,
  "wikiUsername" text
);
CREATE INDEX IF NOT EXISTS "idx_discordlinks_id" ON "mongo_import"."discordlinks" ("_id");

-- SKIPPED discordmusicqueues.csv (reason=empty_header)
-- SKIPPED discordservers.csv (reason=empty_header)
-- SKIPPED discorduserlinks.csv (reason=empty_header)
-- Source: images.csv (rows=11)
CREATE TABLE IF NOT EXISTS "mongo_import"."images" (
  "_id" text,
  "filename" text,
  "originalName" text,
  "mimeType" text,
  "size" bigint,
  "data" text,
  "uploadedBy" text,
  "uploadedById" text,
  "category" text,
  "isPublic" boolean,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint
);
CREATE INDEX IF NOT EXISTS "idx_images_id" ON "mongo_import"."images" ("_id");

-- Source: mediaAssets.chunks.csv (rows=2002)
CREATE TABLE IF NOT EXISTS "mongo_import"."mediaassets_chunks" (
  "_id" text,
  "files_id" text,
  "n" bigint,
  "data" text
);
CREATE INDEX IF NOT EXISTS "idx_mediaassets_chunks_id" ON "mongo_import"."mediaassets_chunks" ("_id");

-- Source: mediaassets.csv (rows=25)
CREATE TABLE IF NOT EXISTS "mongo_import"."mediaassets" (
  "_id" text,
  "originalPath" text,
  "filename" text,
  "mimeType" text,
  "size" bigint,
  "category" text,
  "gridFsId" text,
  "tags" jsonb,
  "checksum" text,
  "metadata.lastImportedAt" timestamptz,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint
);
CREATE INDEX IF NOT EXISTS "idx_mediaassets_id" ON "mongo_import"."mediaassets" ("_id");

-- Source: mediaAssets.files.csv (rows=26)
CREATE TABLE IF NOT EXISTS "mongo_import"."mediaassets_files" (
  "_id" text,
  "length" bigint,
  "chunkSize" bigint,
  "uploadDate" timestamptz,
  "filename" text,
  "contentType" text,
  "metadata.originalPath" text,
  "metadata.category" text
);
CREATE INDEX IF NOT EXISTS "idx_mediaassets_files_id" ON "mongo_import"."mediaassets_files" ("_id");

-- Source: sitehistories.csv (rows=1)
CREATE TABLE IF NOT EXISTS "mongo_import"."sitehistories" (
  "_id" text,
  "siteName" text,
  "siteDescription" text,
  "formationDate" timestamptz,
  "completeDate" timestamptz,
  "siteCreationDate" timestamptz,
  "events" jsonb,
  "milestones" jsonb,
  "stats.totalVisits" bigint,
  "stats.uniqueVisitors" bigint,
  "stats.totalPages" bigint,
  "stats.totalUsers" bigint,
  "stats.totalPosts" bigint,
  "stats.totalComments" bigint,
  "stats.totalLikes" bigint,
  "stats.totalMusicPlays" bigint,
  "stats.totalGameScores" bigint,
  "stats._id" text,
  "stats.monthlyStats" jsonb,
  "stats.createdAt" timestamptz,
  "stats.updatedAt" timestamptz,
  "plannedEvents" jsonb,
  "versionHistory" jsonb,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint
);
CREATE INDEX IF NOT EXISTS "idx_sitehistories_id" ON "mongo_import"."sitehistories" ("_id");

-- Source: spotlightslides.csv (rows=7)
CREATE TABLE IF NOT EXISTS "mongo_import"."spotlightslides" (
  "_id" text,
  "srcPath" text,
  "__v" bigint,
  "createdAt" timestamptz,
  "durationSeconds" bigint,
  "isActive" boolean,
  "order" bigint,
  "tags" jsonb,
  "title" text,
  "type" text,
  "updatedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "idx_spotlightslides_id" ON "mongo_import"."spotlightslides" ("_id");

-- Source: usercards.csv (rows=279)
CREATE TABLE IF NOT EXISTS "mongo_import"."usercards" (
  "_id" text,
  "userId" text,
  "cardId" text,
  "quantity" bigint,
  "acquiredBy" text,
  "isFavorite" boolean,
  "isLocked" boolean,
  "acquiredAt" timestamptz,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint
);
CREATE INDEX IF NOT EXISTS "idx_usercards_id" ON "mongo_import"."usercards" ("_id");

-- Source: usercardstats.csv (rows=14)
CREATE TABLE IF NOT EXISTS "mongo_import"."usercardstats" (
  "_id" text,
  "userId" text,
  "__v" bigint,
  "achievements" jsonb,
  "basicCardsOwned" bigint,
  "craftingAttempts" bigint,
  "createdAt" timestamptz,
  "dailyDropsUsed" bigint,
  "epicCardsOwned" bigint,
  "failedCrafts" bigint,
  "lastDropDate" timestamptz,
  "legendaryCardsOwned" bigint,
  "materialCardsOwned" bigint,
  "rareCardsOwned" bigint,
  "successfulCrafts" bigint,
  "totalCardsCollected" bigint,
  "totalCardsOwned" bigint,
  "totalDropsUsed" bigint,
  "uniqueCardsOwned" bigint,
  "updatedAt" timestamptz,
  "yearCardCompletion" jsonb
);
CREATE INDEX IF NOT EXISTS "idx_usercardstats_id" ON "mongo_import"."usercardstats" ("_id");

-- SKIPPED users.csv (reason=empty_header)
-- SKIPPED wikiconfigs.csv (reason=empty_header)
-- SKIPPED wikidiscussions.csv (reason=empty_header)
-- SKIPPED wikinamespaces.csv (reason=empty_header)
-- Source: wikipages.csv (rows=42)
CREATE TABLE IF NOT EXISTS "mongo_import"."wikipages" (
  "_id" text,
  "title" text,
  "slug" text,
  "namespace" text,
  "content" text,
  "summary" text,
  "categories" jsonb,
  "tags" jsonb,
  "aliases" jsonb,
  "creator" text,
  "creatorId" text,
  "lastEditor" text,
  "lastEditorId" text,
  "lastEditDate" timestamptz,
  "lastEditSummary" text,
  "currentRevision" bigint,
  "protection.level" text,
  "protection.allowedRoles" jsonb,
  "isRedirect" boolean,
  "isDeleted" boolean,
  "isStub" boolean,
  "isFeatured" boolean,
  "views" bigint,
  "uniqueViews" bigint,
  "edits" bigint,
  "watchers" jsonb,
  "discussions" jsonb,
  "incomingLinks" jsonb,
  "outgoingLinks" jsonb,
  "tableOfContents" jsonb,
  "templateInfo.isTemplate" boolean,
  "templateInfo.parameters" jsonb,
  "revisions" jsonb,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint,
  "editLock.isLocked" boolean,
  "editLock.lockReason" text,
  "protection.reason" text,
  "protection.protectedBy" text
);
CREATE INDEX IF NOT EXISTS "idx_wikipages_id" ON "mongo_import"."wikipages" ("_id");

-- SKIPPED wikirevisions.csv (reason=empty_header)
-- Source: wikisubmissions.csv (rows=18)
CREATE TABLE IF NOT EXISTS "mongo_import"."wikisubmissions" (
  "_id" text,
  "type" text,
  "status" text,
  "namespace" text,
  "targetTitle" text,
  "targetSlug" text,
  "pageId" text,
  "content" text,
  "summary" text,
  "editSummary" text,
  "categories" jsonb,
  "tags" jsonb,
  "expectedRevision" bigint,
  "author" text,
  "authorId" text,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint,
  "reason" text,
  "reviewedAt" timestamptz,
  "reviewedBy" text,
  "reviewerId" text
);
CREATE INDEX IF NOT EXISTS "idx_wikisubmissions_id" ON "mongo_import"."wikisubmissions" ("_id");

-- Source: wikiusers.csv (rows=10)
CREATE TABLE IF NOT EXISTS "mongo_import"."wikiusers" (
  "_id" text,
  "username" text,
  "email" text,
  "password" text,
  "displayName" text,
  "avatar" text,
  "bio" text,
  "signature" text,
  "role" text,
  "permissions.canEdit" boolean,
  "permissions.canDelete" boolean,
  "permissions.canProtect" boolean,
  "permissions.canBan" boolean,
  "permissions.canManageUsers" boolean,
  "edits" bigint,
  "pagesCreated" bigint,
  "discussionPosts" bigint,
  "reputation" bigint,
  "preferences.theme" text,
  "preferences.timezone" text,
  "preferences.emailNotifications" boolean,
  "preferences.showEmail" boolean,
  "preferences.autoWatchPages" boolean,
  "isActive" boolean,
  "isBanned" boolean,
  "lastLogin" timestamptz,
  "lastActivity" timestamptz,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  "__v" bigint,
  "banStatus.isBanned" boolean,
  "warnings" jsonb,
  "discordAvatar" text,
  "discordId" text,
  "discordUsername" text
);
CREATE INDEX IF NOT EXISTS "idx_wikiusers_id" ON "mongo_import"."wikiusers" ("_id");

-- Source: wikiworkshopstatements.csv (rows=58)
CREATE TABLE IF NOT EXISTS "mongo_import"."wikiworkshopstatements" (
  "_id" text,
  "issueNumber" bigint,
  "speaker" text,
  "message" text,
  "listAuthor" text,
  "listAuthorDisplayName" text,
  "listAuthorDiscordId" text,
  "isSpeakerOfYear" boolean,
  "createdAt" timestamptz,
  "__v" bigint,
  "updatedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "idx_wikiworkshopstatements_id" ON "mongo_import"."wikiworkshopstatements" ("_id");
